title: AIWise
lang: en
description: test

remote_theme: Guangzhou AIWise Artificial Intelligence Technology Co., LTD

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock